package itaxi.communications.message;

public enum MessageType {
	REGISTERSTATION,
	PARTY,
	BOOKFLIGHT,
	SHIP,
	GETSTATIONS,
	GETSTATIONDETAILS,
	INITVEHICLE,
	GETVEHICLEDETAILS,
	GETSTATISTICS,
	MONITORMAP,
	UPDATEVEHICLE,
	CLIMBALTITUDE,
	DESCENDINGALTITUDE,
	COMMUNICATE,
	STOPCOMMUNICATE,
	SENDVEHICLE,
	FLIGHTRESPONSE,
	POWER, 
	ENDFLIGHT,
	FORCEBATTERYFAILURE
}
